### ISSUE TITLE
Error Message: "can't convert float NaNto integer"

### ISSUE THREAD

**Issue by miguelpavaodelgado** [fmi-faim/napari-psf-analysis#19]
This error appears in a lot of the files (would say around 1/3). 
In the month of october i got it in the following files:
Z:\Maintenance_All_microscopes\Maintenance_W1_Levi\Maintenance_weekly\PSF\20221031
W1_Levi_63x_3_Conf488

Z:\Maintenance_All_microscopes\Maintenance_W1_Levi\Maintenance_weekly\PSF\20221017
W1_Levi_63x_1_Conf488
W1_Levi_63x_2_Conf488

Note that I am using PSF Box size = 4000

![20220829_63x_9](https://user-images.githubusercontent.com/80036347/199793635-c7581f11-0221-4755-acfd-ca0b7f2eb03a.png)

**Comment by tibuch** [comment]
Hello everyone,

This issue should be solved with the new version 0.2.3. You can install it by running pip install napari-psf-analysis --upgrade.

Happy analyzing!
