### ISSUE TITLE
Cannot convert float NaN to integer

### ISSUE THREAD

**Issue by Lplantard** [fmi-faim/napari-psf-analysis#21]
Hello, 
I am getting an error message when analysing files. It says Cannot convert float NaN to integer. Data acquired with a different objective on the same microscope work well. I do not know if it's a problem of scale (pixel sizes are different). If I set the PSF box size to 5000nm then it works. 
![Napari-PSF](https://user-images.githubusercontent.com/56690254/202181579-eacc1a0a-f0a5-4008-a7de-6dade6d4a1ec.PNG)

Then with another file, same system, same objective, it does compute the PSF with a box set to 6000nm, but I get the message: overflow encountered in multiply. 
 
I can give you files if needed. 
[20221114_PSF_Stellaris5.lif - 20221411_60X_1.tif.zip](https://github.com/fmi-faim/napari-psf-analysis/files/10021837/20221114_PSF_Stellaris5.lif.-.20221411_60X_1.tif.zip)

Cheers

**Comment by tibuch** [comment]
Thanks for reporting @Lplantard. I improved the fit robustness and the new version (v0.2.4) should soon be available for install.
