### ISSUE TITLE
A bug for my first try

### ISSUE THREAD

**Issue by pierre-weiss** [fmi-faim/napari-psf-analysis#51]
Dear all, 

together with Laurent, I just tried the plugin with an image from a wide field microscope with z-stack and got the error below 
 
![error_psf_analysis](https://github.com/fmi-faim/napari-psf-analysis/assets/19427204/bb415594-54f2-4f42-b6ef-0b9d6e424d53)

Can you help ?

**Comment by tibuch** [comment]
Hi @pierre-weiss,

Thank you for reaching out. The error indicates that no fit was found after 2400 iterations. 

Can you share the configuration parameters you used? In particular the pixel size, spacing and bounding box size. Maybe reducing the bounding-box size can help.

Kind regards

**Comment by pierre-weiss** [comment]
I used the default set, I sent the image to Laurent.

Best,
Pierre

**Comment by tibuch** [comment]
The default pixel size is most likely wrong for your data. I have opened #52 to address this issue.

**Comment by pierre-weiss** [comment]
Thanks a lot!
