### ISSUE TITLE
error: "NapariReader" object has no attribute "copy"

### ISSUE THREAD

**Issue by Lplantard** [fmi-faim/napari-psf-analysis#54]
Hello, 
Trying to analyse PSFs I got the following error message 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\Anaconda3\envs\PSF-analysis\lib\site-packages\napari_psf_analysis\_dock_widget.py:416, in PsfAnalysis.prepare_measure(self=<napari_psf_analysis._dock_widget.PsfAnalysis object>)
    415 def prepare_measure(self):
--> 416     img_data = self._get_img_data()
        self = <napari_psf_analysis._dock_widget.PsfAnalysis object at 0x0000025BCE3CB1F0>
    417     if img_data is None:
    418         return

File ~\Anaconda3\envs\PSF-analysis\lib\site-packages\napari_psf_analysis\_dock_widget.py:549, in PsfAnalysis._get_img_data(self=<napari_psf_analysis._dock_widget.PsfAnalysis object>)
    547     img_data = np.transpose(img_layer.data.br.read(), [2, 0, 1]).copy()
    548 else:
--> 549     img_data = img_layer.data.copy()
        img_layer = <Image layer '20232220_W1_Franklin_40x-id57_1_conf488' at 0x25ba1120070>
    551 return img_data

AttributeError: 'NapariReader' object has no attribute 'copy'

**Comment by tibuch** [comment]
Re-installing from scratch solved the issue.
